languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "A bioinformatics learner"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Boleyn"
  image = "img/blowfish_logo.png"
  headline = "A bioinformatics learner"
  bio = "Single Cell、Spatial Omics、Machine Learning"
  links = [
    { twitter = "https://twitter.com/burufugu" },
    { mastodon = "https://masto.ai/@blowfish" },
    { github = "https://github.com/boleyn0205" },
  ]

  